<?php

// EveryAction has IDs in the URLS, but they are encoded in a strange way.
// Really hard to work with when you have a download/spreadsheet and want to look at a lot.
// So this is a simple bounce script.

// Mostly Generated by Gemeni based off of https://untitledspreadsheet.com/everyaction-url-formulas
// Then tweaked a bit by mblain.




function getEveryActionId($vanId) {

    // Ensure the VANID is handled as an integer
    $vanId = (int)$vanId;

    // 1. Convert VANID to hexadecimal format
    $hex = dechex($vanId);

    // 2. Reverse the characters of the hexadecimal string
    $reversedHex = strrev($hex);

    // 3. Calculate the checksum suffix character: MOD 17 + ASCII value of 'A' (65)
    $checksumChar = chr(($vanId % 17) + 65);

    // 4. Combine into the EID parameter format
    $eid = 'EID' . strtoupper($reversedHex) . $checksumChar;

    return $eid;
}

// Any invalid path option will be considered to be contact.
function getPath($option) {
    $allowedPaths = [
        'contact'      => 'ContactsDetails.aspx?VANID=',
        'payment'      => 'PaymentDetails.aspx?ContactsContributionID=',
        'contribution'      => 'PaymentDetails.aspx?ContactsContributionID=',
        'source'       => 'SourceCodeDetails.aspx?CodeID=',
        'activist'     => 'ActivistCodeDetails.aspx?ActivistCodeID=',
    ];
    $targetPath = $allowedPaths[$option] ?? 'ContactsDetails.aspx?VANID=';
    return $targetPath;
}

// 1. Check if the 'vanid' parameter exists in the URL
if (isset($_GET['vanid'])) {

    // 2. Validate that the input is a valid positive integer
    // filter_var cleans the input and returns false if it's not a proper number
    $inputVanId = filter_var($_GET['vanid'], FILTER_VALIDATE_INT, array(
        'options' => array('min_range' => 1)
    ));


    if ($inputVanId !== false) {

        // 3. Generate the URL if validation passes
        $eid = getEveryActionId($inputVanId);

        // 2. Read and get the path.
        $rawPath = isset($_GET['path']) ? trim($_GET['path']) : '';
        $path = getPath($rawPath);

        // Todo: Figure out how to make audit work. For some it's simple, others the URL has the eid more than once.

        $everyActionUrl = "https://app.everyaction.com/" . $path . $eid;

        // 4. Output the link
        //echo "<a href='" . htmlspecialchars($everyActionUrl, ENT_QUOTES, 'UTF-8') . "' target='_blank'>Go to EveryAction</a>";

        header("Location: " . $everyActionUrl); exit;

    } else {
        // Handle invalid formatting (e.g., text, decimals, or negative numbers)
        echo "Error: The provided vanid must be a positive whole number.";
    }

} else {
    // Handle missing URL parameter
    echo "Error: Missing 'vanid' parameter in the URL. Example usage: script.php?vanid=12345678";
}
